### ISSUE TITLE
Update QGIS Installation instructions

### ISSUE THREAD

**Issue by spatialthoughts** [spatialthoughts/courses#138]
QGIS.org has a new website and our instructions need to be updated with new screenshots
https://courses.spatialthoughts.com/install-qgis-ltr.html#

**Comment by Kulaumone** [comment]
Good day colleagues,
I am seeking help, i have been trying to QGIS software and all the version are not displaying features symbols in the symbology. I am using a HP ELITEBOOK core i7, 8 gen, window 11. what might be the issue?
![Screenshot 2024-07-12 163520](https://github.com/user-attachments/assets/b03c84ef-589d-4529-9f46-6566edc98b1a)

**Comment by spatialthoughts** [comment]
Fix in https://github.com/spatialthoughts/courses/pull/142
