### ISSUE TITLE
Whitespace missing between number and unit

### ISSUE THREAD

**Issue by phidrho** [spatialthoughts/courses#145]
By SI Standard, there should be an space (whitespace) character between number and unit, see [Unit symbols and numbers](https://en.wikipedia.org/wiki/Space_(punctuation)#Unit_symbols_and_numbers)

https://github.com/spatialthoughts/courses/blob/d03e7e1279ffe52cd3c34e621ad5693e4a8f18aa/code/python_dataviz/08_interactive_maps_folium.ipynb#L324

https://github.com/spatialthoughts/courses/blob/d03e7e1279ffe52cd3c34e621ad5693e4a8f18aa/code/python_dataviz/08_interactive_maps_folium.ipynb#L451

**Comment by spatialthoughts** [comment]
Thanks for fixing these. Have fixed in the source and will go out to the website and data package in next week's build.
